import type { MetaAd } from "@/hooks/useMetaAds";

export const DEMO_META_ADS: Partial<MetaAd>[] = [
  {
    id: "demo-ad-1",
    page_name: "Acme Fitness",
    ad_creative_bodies: ["🔥 Flash Sale — 40% off all home gym equipment. Limited stock, ends Sunday. Free shipping on orders $75+."],
    ad_creative_link_titles: ["Shop the Flash Sale"],
    ad_creative_link_descriptions: ["Premium home gym equipment at unbeatable prices."],
    cta_type: "SHOP_NOW",
    ad_delivery_start_time: new Date(Date.now() - 5 * 86400000).toISOString(),
    is_active: true,
    publisher_platforms: ["facebook", "instagram"],
    platforms: ["facebook", "instagram"],
    spend_range: { lower: 500, upper: 1500 },
    impressions_range: { lower: 50000, upper: 150000 },
    estimated_audience_size: { lower: 1000000, upper: 5000000 },
    currency: "USD",
    media_type: "image",
    first_seen_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: "demo-ad-2",
    page_name: "Acme Fitness",
    ad_creative_bodies: ["Tired of crowded gyms? Build your dream home gym with our 2024 Starter Kit. Everything you need in one box. 🏋️"],
    ad_creative_link_titles: ["Get Your Starter Kit"],
    ad_creative_link_descriptions: ["Complete home gym solution starting at $299."],
    cta_type: "LEARN_MORE",
    ad_delivery_start_time: new Date(Date.now() - 14 * 86400000).toISOString(),
    is_active: true,
    publisher_platforms: ["facebook"],
    platforms: ["facebook"],
    spend_range: { lower: 1000, upper: 3000 },
    impressions_range: { lower: 100000, upper: 300000 },
    estimated_audience_size: { lower: 2000000, upper: 8000000 },
    currency: "USD",
    media_type: "video",
    first_seen_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: "demo-ad-3",
    page_name: "FitRival Pro",
    ad_creative_bodies: ["Join 50,000+ athletes who switched to FitRival Pro. Our AI-powered training plans adapt to YOUR schedule. Start your free 14-day trial."],
    ad_creative_link_titles: ["Start Free Trial"],
    ad_creative_link_descriptions: ["AI-powered personal training that fits your life."],
    cta_type: "SIGN_UP",
    ad_delivery_start_time: new Date(Date.now() - 21 * 86400000).toISOString(),
    is_active: true,
    publisher_platforms: ["facebook", "instagram", "messenger"],
    platforms: ["facebook", "instagram", "messenger"],
    spend_range: { lower: 2000, upper: 5000 },
    impressions_range: { lower: 200000, upper: 500000 },
    estimated_audience_size: { lower: 5000000, upper: 15000000 },
    currency: "USD",
    media_type: "video",
    first_seen_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: "demo-ad-4",
    page_name: "FitRival Pro",
    ad_creative_bodies: ["⭐ \"Best fitness app I've ever used\" — Sarah M., verified user. See why we're rated 4.9 on the App Store."],
    ad_creative_link_titles: ["Download Now"],
    ad_creative_link_descriptions: ["#1 rated fitness app."],
    cta_type: "DOWNLOAD",
    ad_delivery_start_time: new Date(Date.now() - 7 * 86400000).toISOString(),
    ad_delivery_stop_time: new Date(Date.now() - 1 * 86400000).toISOString(),
    is_active: false,
    publisher_platforms: ["instagram"],
    platforms: ["instagram"],
    spend_range: { lower: 800, upper: 2000 },
    impressions_range: { lower: 80000, upper: 200000 },
    estimated_audience_size: { lower: 3000000, upper: 10000000 },
    currency: "USD",
    media_type: "image",
    first_seen_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "demo-ad-5",
    page_name: "GymShark Competitor",
    ad_creative_bodies: ["New drop alert 🚨 Our Spring Collection just launched. Use code SPRING25 for 25% off everything. 48 hours only."],
    ad_creative_link_titles: ["Shop Spring Collection"],
    ad_creative_link_descriptions: ["Limited edition activewear, designed for performance."],
    cta_type: "SHOP_NOW",
    ad_delivery_start_time: new Date(Date.now() - 2 * 86400000).toISOString(),
    is_active: true,
    publisher_platforms: ["facebook", "instagram"],
    platforms: ["facebook", "instagram"],
    spend_range: { lower: 5000, upper: 15000 },
    impressions_range: { lower: 500000, upper: 1500000 },
    estimated_audience_size: { lower: 10000000, upper: 30000000 },
    currency: "USD",
    media_type: "image",
    first_seen_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
  },
];
